### PR TITLE
Refactor metadata extraction into its own function.

### PR DESCRIPTION
**Pull request by smashwilson**
This should clean up our FG and NG server iteration loops quite a bit.

### CODE REVIEW

**Comment by smashwilson** [comment]
@jrperritt Mind looking this over to see if I screwed anything up?

**Comment by smashwilson** [comment]
It works for me, but I'm not testing against any first-gen servers.

**Comment by jrperritt** [comment]
Looking...

**Comment by jrperritt** [comment]
Working for me, too. Do you want to change the output to be more terse in this PR?

**Comment by smashwilson** [comment]
Nah, let's keep these self-contained. I'm working on cross-compilation now in a new PR. I could do that later unless you want to grab it.

**Comment by jrperritt** [comment]
:+1:  LGTM

**Pull request merged**
